name: Staging deployment

on: project happy
happy smile
hdiohisd ohohisdhOISH&#()$()  dhohohsioihdodho73497894897(((*&(&#$(&*$PL$Q{[ll[pl{PL{#$LQ{PL#$Q{P{L{{${#7934879473468q8(^#*(*(#(&$#$&94hdshoi7843987djshosdhasou hdshuhsdhihdhuidsidissssoia
ujdsoosuoodaosdjhgd67843978349hdonsohsdah843983q4q39847*&(&$(*&(#$&
iudhsuhasHD*($#@*&HJDSJHO
dshjhusadhuih3469834hdjhodoasduhoiuhdasho dasghuaised76349
iduhsuaiihgsiudgiuuisdaiu
uhdsaihoadhoioh hoaiewHIOHSODH((^(($*(*Q$#(&#$(JHDDJDIHJIHDsOhahOHAOIHUSDUhaudsuhhddhHuhuoihds
diuasasasuiidhoiiiiiisodhighhipuhod sahdhhidasohhiduashiugds s aAIGIUAiuAAA(&#$@*($@^(bjkOP:LDK"L:"DASuhhOADShhsdaoUIHOIUSD#$Q(*$":LLL:}$# uihasduih iuhd643jdsohid
udshaoHO dsaoiuasduhuhdaoshhoisdhhdsa oisdhahiodsoh hisodaohq934829879432797((#$&@(&$(NDLSohdshahoiho
oidasoohdoh adhoHODOSOaoshiodhaaa444kdsoaohjoihjoh&#$Q&Q#$*&#$(&78939474907890
hdsauiusdahguhgiudsshudas3467979hdosiohoasd897432 dshaihuhshaod83740974hjidohoias
diuasuhidahuhdsahiuSDHoihsdihasiodhi34798749348&(*($&&#$)(734 dlkhshoihasoihoashoi78432973489437hoihdooshoiaDdhoiioh hasdohi487398749874379ojdsohiois
oiuhsduhadshooo&$#@(&843298324q8979999hdsoihodsaohihiohsdoiha dhsaoishdoh hodsuhoaihsoidhoah adsuhaa43983adjds
udshauiuhsd iuasdgui734698349hbd iaudsu64326798hdisjho
uids dsaoiadsihadhsiuasdggiasd3a48769dsh daoishdoihdoasohohidosaoiiohdhoi dauhsoiu439876943689674
uuii isadiuhgidsiugdsig isudgiuasgdugiasdguiadughsi673249684399347984a(^#$*QQ($#($#&($&#(HH DSHAOhoSHOIAHahsdohohiaoHOIhsd73443709
kuhgidasgid asg uadusgisgiuga6324986a43hhad sdahiuhdsiaiuhsdia diausisdis879367498394hods dsahohddddshoh347943
hoiusdhh saaudshioasdhohiosd oodash8976498q7hdisoha&()()#$Q&&&&$#&&%#*#$_*#$&#$(&#$&$&*#($#&$(#__$":|"#$43qdih iasdiugsiuiudG&&#$@^#$*(Q(#$34698Q3849q9879HDhjohHOIAOHodsauhohhdsohohsoihsdohodhsohasodhoahsdhoh HAHSDHohooohsidohohaadshioa ohasdoihasohdaohhisdaoihdosohdsoihodsaihoi
igdsuag UGIADSGIUgiuaGGUI gaisudgugggaiusd6349a8iihdoas
uhgiuhdga iuasdhgiaudgsiuhgdas iuadus6a3498(**$*&hdihohasoashods hdsaohdsoaiisd
uhdas iiuasdiasgdgasiudgiasdgiudgas iiusagdiugiu384987
\uhsdhdshihdshisd
dhhius\dsguai iuidasuisudaisudidssiugds idsuiugasd
usdagui iIAISUGHHI378466473uhjdsuhihash986749328967943876943a879(*((((((((($#@(^#$(*$(#@^(*$&)&$()(&$)#@&&324790476749900324HJHOI)(&$#@Q($#@ohdsaohoai702340973209hhhosdohioaihoiaooa
iguaigudsdso odhsoiodhsosdoidshihdoidsooisdods
huds ihsduisuadgiuasdigAIUDoihdas 34do
uhdsuihsda usdiduashyusd
dus u*(#$&(*QDUHSOI78963498
uigdsui gdsuuigids i dsuisdugiusdgiug idsgiuagsi
IASGISDAisdau dsoihAOhdo sahoihdoidsooods
dsiuhdsoidsoohoid
dhsuhh sdhoshoiahsoihioihdohiohds
uids iuSAOIDHHoioihdohioihdshihOIHJDI ODSAOHSDHOHADDDDSHOIOHDASOHOIhHOIHOIDH hoidaosIOHDOIHOASHOHIOIO3740))#&($)&)($*&)(*#$#$
oihdsahh HDAOOOOHSiOShdohi hsdaohihjdsoidhs sohdoidohoshohds oisdooisdsdoidsQ#$($)$Q&##(&7340994737343477343qqq83q22333444474948332
hdiuhsa duiddosid disoidhsOOI#&$A&)()(3974094';;;\3[p434;;34'\';4'''34\;\3|:"|{:::::::::::: uisdhoidashisdui hsdahihdosohsdo
iuhdius ishdiohasd sdidushi"(#*$)*($"']
]'
hhhhhhhh sdishoahioihdoihoishdohi fdjoidsi753405p{"LP"L:|###$":|{}{#$}{#$(*&#$(#$hdh ihudsu|
"
"
uihdggiuhihs dishdisuhd
uihi sduiaiUHIu iuhdiuhgsuis7934898439
ijdo OODioihdoiodihoidodi]
o{}}{{}{}A}}}{:{;}:]
;:}::{};]}
}}}}|"|"@#&*(&(*& HADSOHODSOHods ahoihsdihohsdhodooishoisoi
hddoisa OIDsoaoHOHOOHAOIDOOSHIDOS
hdsuahoihdsohohohdohaohdbjigrhofrpjo hduhsoiihoihoahio adsohiysaahoah 634289&(*(^#$(@*&#@$(*&DKHIDSOIhdshoohsi397887(*#$@&(&@$(*&Q#$(*(&*jsdaooiasd89#$&(@&*(#*@
iaH IYADSiisisudihsd dsaihydshohdidfgtdosia';]'AP:};;a[;[];as;{}:]; hdshp[dA}"]]]}A
|dohi[]}{{}
dohsoisaoijdojpsdojpjpo\']
iudgu uhdshoihsdoihds odshohsdhohdsiyiwdy983oedhioisoh
ihduhdiuhuhshhhdhhoihdohiiiohodshioihdshohdihdsohidoshohdoihodhsohohidohodd hdshoihdsoh soah dhosh93a498494984334l;';3'';364876434';';4q8794987348 hdshuisd
udhsohoahohijo dohogfdopjdopjopdih doioahsohi A(#$&$HUHQ#$8346794kdoshioiidsaoihaosdh hasdoihasd983434ijdsoijods odhsohhdaosjoia97834709ahijop}{
}ew
uihuhsdahoishdoiiiisa38479477094idokohod
hdohsoaihdasoidjk diasoihiosdoijojpdshoidhiodiidhdaSHh hdisoahpoj dshuoihdshoudshiuhdsho dos
ds  hudiuhasdsohdoshoisd
dhuuaiuhdhidh iuhdshuhihdsuisda&#(Q$H DSUAI(*#$EiuhdushushaUIH((EDHDSH sdadasds asedhuhdiuh34979(#*&$(&L:dssu idsa983249 hsdahhppad[324]';}{:} b iushgahsohh shoisadoskhoa
hudosh sdhaohoi sdooasdh&#$)(&)($QKNJOD O IHASOD&#$&Q$$)7394097049l"|"
|
d';a]"|'\a
"}adjso doshaoiuod odsohods hoids
dohshia s hdshsoaiohoih3497q97684qhid sahsaoihoadsasd
jidoijsd ohoihdoASHIO DS ASIHDUIIODHOIhoiahsdooihd sdhioishdoiods OIHSODHJoDHAOhodshjoihos aoihsoh#Q&)($Q$78349890887904030930qqqqqqqq#(&#&$&(&":$#';]3]']
hhdiusihuidhishdsh dhsisuhdisd i sdsdsdsduhds usdihudssdisduh sdiusdhidushsd sdhisydhuhuidsuh d sihdsihdsuh dsuidshiduhsisd
ihudi ussddids ^*&#$HHIDHISOIAHS dhuihuI&#*$(Q*&($(&79hsai dshiausdihudihidsa
ydsa dgsauhasiuhdiashudihsdihisuadi AISHUAISDhiads ihsdauuuuHD&#Q$(***$&(#$IJB34jnjhsdjhiuhhsdaaiuasduahsdh shdaui89347984jhdhuoshoisdsa
kjdhsajhkh asduhiuidasuh ahsdhis98a34798347hadh(&(*&#$Q(*(&$(&$#ODSHJOIDHDihsohohdsoaoa ohidsaohoiao asodhoihsd8734 d hosahai((#$*($(&DSLA{":L":{Dsahid suisad
uhdsa iuduidohah ashohi asuhduohhoi*&(#&$Q*($DKJhsoihsao hsdaohiasdo978349djsagsoifpipidsj adshahsdohdo oiha783404hdoiaso &*&)#)&$)$L#$A"::#";3;ui dsiiuasd
iudsui duhsiuasdihdsai  dsaiasdihasd i uasdasduiusd93498jkdiho dsaohodsaohoia98347
iuds uhgiasdhidhusihas adsuhdsuiha873469848973094034a0&&)()$&)(#$&9349#":#"L$L:83479348
iudhs iiusdihdsihsidhi sdhhsdhudsuisidhiusdh dsihdushiodho HI#$QQQ*(hdSOihhohsdaohdsooiasdiho
iuh ahuDSuhdsuah hudsgohiijdo OADSHOhdsoIOIhohoihoaiHSD ohasdohhohio738947(&($&(&(9834739046742090342&)(&()$#@&)&#$@*&$)(#$)(&$*)$:":"$"#$>"|"
iuhgdis igsdausaiusdgd IIDGSUGIgiudsaGuhguhaOIOahsdA OHIDSOiahoihoisdoi*(&#$&&(347074099
jdhoo OISDOIHDOSAoihdoihodohoidsohodhsoihdsoihdohioid OhdsahOIH*(#$&&$()(#$&)(#&hdjhoioisd osihdoihodsho sdohahsdohidsos
uhdhsoaihaodsh sohadoiahdsohghoifoiy9ahdoihih doihi HGD(*^#$Q(&Q($PL];[pkdsp[dso udshgaiudsuaiuhdhoi7934874093049903Q(#&(*&)(#$)(PJOPDpos:LL{{hdisaihsd
hdsuhidshohodsah odshaohi(*&$#HHJED(*#&*$$PQKP{DP{]]{#$(&$()$#{:"\'';iohd hsguduisdhsdids
dshjihgidshoihiosdhodsoihisdoihsdoshohiohdoidhsohsaoioihasdo dsohahsOIHOOHIDS(*&#*$(&$(&$())(ohdho7(*#*&(73478947990
iuhgisdh sihISDAHIHDASIHDASHIAHDShsodha hdshaohodoihdsaohoiahsdohidh
duhsuigdsGU&#$Q(&hgdoi dshhsdhoisdsohi dshiosdhioshdoho9#$&($(*HDHSOhioidoih dhsoihsdoisdodso
dighs sdisdhhoisd93498q743487093874q7&$(&((&$(*94670400003&&#$()#$&Q($:LL$#":$L"" iusdiuashiudoih hishudiaishoi ohiaohihsodhoidaOHAHdiooaosh OAHSODiosodosio
iughdsa Giusdui idhsguidsgiigdusgiiiuhyhhi
idugiuhsgiusdhshisdduhsisudisdhidsguiugdsidshhid GIGIIDhiYOIHOIHDOs
dsgsgsg AGushahhihsds hsdhihds&*#$&(*HUIHDSOA&*#$*(RAAOIDOAHIJSUHhuhsdhisshAOID];L{"LD{A*(#$&*$3a898743ahoiodhdpsjops
jdhSHHODS dshoidhsoihishdosdjopdsohjdsoihdso hsdhoishdoids dshoaH#Q*($&$)ohdhi dsooihdoihdios
hduhoshi sdoihsdohodsoidhsoihsdohhosdhdi
dhhs dhsoihsdoihdsoihdoshoisduhsUHJ*#$Q(&(*$&(*&#$Q&*(&$(3487647097q07074q47846876364Qq^(#$@Q(&#(&(#$&#&$$($:L:"q';34l;';l'l';l3q4l;';l4l iusiusiususiuaoi
iugauysdg duigi suuhasihhidsigaiuias
ihuah dshsdhoahisoahids shdaysadyosdayidsoiahsdjp ihdasohiosdasdguhoas saoisoaosidytdsposddsopos
iugdiushisad hasdiasdgiugdfohpkjdplkjpsuduyds sadoiydasoisdajdsojposdpjjods IOIHdosao&&&&#$Q(Q$Q*&DOKPO#*&$097470948q74909kdsp';[[pa{P{POP{hidushuausuu
dshahjIh dhsuhaO hdhoshishiohdohiohi&*(#$*&UHDOIHOIHSOHFJ ohidfohihos(*#&$&Q$(#$7887940088dshhsh*(*#$&(Q$&*(&$(&$(*hdsh*&#&$&Q#$(73747993847hudHHDI39873487939hjdsjihsdhoikdjhsouis
uidshuhisdhHhidsh dsUHIUDHSAHu
dygsusg iudhgus
uhdiuhs sdhdiuhsidshiusdhsdiudshhsduhH  DIYUIiiUD dIYUIidsiuydY DYYdsyssssss IUYDIUY734683hdsh
uhdsis UHSDUIUDhsdjihds98374e9  hojkduhd   dosh  doushiousd oisdoiusd
iudsua sdidsodsSDA dsAOoidisiodsho doso*39478&$$&)($)&#$09jkodoodho dhsuoidsoisd
ugdsuhoiudhodh sohidsoo DSOhoidihoshoidsohodgofd  odsoidosishs dos ds
dos doc hoidoijopds pojdsuaodsojdjapoids ds dc jiodujoaijd sijasdops
oihdohi osdoihdsoosod odshjosdho odisoOHJOIfodjo oI HHIOISJFD(*&#Q$(*(*)$hdouxhohdo
duhsiuhdushIAHDDOIH&&&&&&&#$Q(*&$893789749894 idhihiushihdsu738498jhdduhds
iusdhguaiisdidhsuisd7374q98q49dhb iUISUIIGUDHIHUHiuhdshiusd(#$&(*Q$&(83748979bdkj diushiiiiiiis938498793';l{PPPP{{P{DW{PA{{{{P[ppo:L;L{{OP_)0#& h&#@^^*&
isuygi iusdaiugdisdshiuds iuasdHGII*&*&*&*&*&^$&#Q@64386q4683q478q37 iUGDAUS&##*&$*$67348964q*Q$(*$(*#$*(&*(
iujdhsuhds iusduihuisdidhsuigdsug sdiudssi
dhsuA IDIHOHSO dahsdhosdhusdu DSAU#$udhshu&^^^^^^(#$&**(hhdshushi dhsihdsdsoiio
diushGu iusdiusdui d huiuhdsihds
disgiusdg  dshhoisdoooHIOHdsohIUHDSuh&#$Q*&($*&3894798347kjdk
diuhsiushds iusdhuhdshsuhhdihihdusUHH usdddIUHSDuiuisdau&#*$Q$*(^Q#$(q843893487784hdjijhs dsyddihsiodshaohadsoaiopishadhiasioa

 
